export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  USER_REQUEST: "USER_REQUEST",
  USER_CREATED: "USER_CREATED",
  USER_FAILURE: "USER_FAILURE",
};
